--
-- Файл сгенерирован с помощью SQLiteStudio v3.4.4 в Ср окт 25 16:24:10 2023
--
-- Использованная кодировка текста: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Таблица: Items
CREATE TABLE IF NOT EXISTS Items (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, name TEXT NOT NULL, type INTEGER NOT NULL REFERENCES Types (id), year INTEGER NOT NULL, space INTEGER NOT NULL REFERENCES Spaces (id));

-- Таблица: Spaces
CREATE TABLE IF NOT EXISTS Spaces (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name TEXT NOT NULL);

-- Таблица: Types
CREATE TABLE IF NOT EXISTS Types (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, name TEXT NOT NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
